# Generated by Django 3.2 on 2021-05-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=100)),
                ('user_pw', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=300)),
                ('title', models.TextField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('analysis_date', models.DateField(auto_now=True)),
                ('channel_name', models.CharField(max_length=100)),
                ('video_time', models.CharField(max_length=20)),
                ('topic', models.TextField(max_length=300)),
                ('user_idx', models.ForeignKey(db_column='user_idx', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user')),
            ],
        ),
    ]
